# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20171122_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvite',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='familyinvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familyinvite',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 10, 14, 28, 516038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 10, 14, 28, 516038, tzinfo=utc)),
        ),
    ]
